apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mailhog
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /tmp/pv-mailhog
