apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mailhog
  namespace: default
  labels:
    app: pvc-mailhog
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeName: pv-mailhog